version: '3'

services:
  nginx:
    build: .
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/letsencrypt/conf:/etc/letsencrypt
      - ./data/letsencrypt/www:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped
    volumes:
      - ./data/letsencrypt/conf:/etc/letsencrypt
      - ./data/letsencrypt/www:/var/www/certbot